### ISSUE TITLE
Hey, I would like to contribute to this project, can you pls guide me ?

### ISSUE THREAD

**Issue by ankitjain28may** [Webiny/Webiny#1]

**Comment by adrian1358** [comment]
Hi @ankitjain28may,

happy to see you're interested in contributing to Webiny.
 
At the moment we are finalizing our documentation and the contribute guide.
In the next week or two we will do a public launch and then ping you back on this
ticket with the next steps. 

Thanks again and glad to have you on board!

**Comment by ankitjain28may** [comment]
Thats great, Thanks :)
