### ISSUE TITLE
Missing I18N

### ISSUE THREAD

**Issue by inluxc** [Webiny/Webiny#2]
In a new isntalation is missing this module.
```

vendor.js:22732 Uncaught Error: Cannot find module "./I18N"
    at webpackMissingModule (vendor.js:22732)
    at Object.4e5f36ba1d (vendor.js:22732)
    at __webpack_require__ (vendor.js:21)
    at Object.ea7e0636b5 (vendor.js:67956)
    at __webpack_require__ (vendor.js:21)
    at vendor.js:20293
    at Object.4474af9d4d (vendor.js:20326)
    at __webpack_require__ (vendor.js:21)
    at Webiny_Webiny_Core_Vendor.0.module.exports (vendor.js:63)
    at vendor.js:68
```

**Comment by Pavel910** [comment]
Hey @inluxc, thank you so much for giving Webiny a go!
I just released a new tag, `1.0.1` to fix your issue.

To get the new version you can simply run `composer update webiny/webiny` from your project root. Run the development build after that and you should be good to go :)

Can you please tell me what environment you are using, and your host OS?

We are developing this on OSX and Ubuntu and never noticed this case letter problem.
Thank you for your time!

**Comment by inluxc** [comment]
Using Ubuntu.

**Comment by Pavel910** [comment]
Ok, thanks! Hope it works for you now :)

**Comment by inluxc** [comment]
Its still giving the same error... with the update.

**Comment by Pavel910** [comment]
Please update. Version `1.0.2`. There was still one wrong letter. 
It is interesting, however, why we can't reproduce the problem on our local machines.
Please let me know if the problem still persists.

Thanks

**Comment by inluxc** [comment]
MacOs = case insensitive filesystem
Linux = case sensitive

**Comment by Pavel910** [comment]
Well, I am running Ubuntu on Vagrant, and my webpack builds are running on that same Ubuntu (I ssh into Vagrant box and run the cli tool from there) so Linux rules should apply. Am I missing something?
