### ISSUE TITLE
Cannot add new Sorter to QueryContainer

### ISSUE THREAD

**Issue by adrian1358** [Webiny/Webiny#5]
Currently QueryContainer only accepts an instance of Filter:

```
 public function add(Filter $filter)
    {
        $this->filters[] = $filter;

        return $this;
    }
```
But it should accept instances of Filter and also Sorter.

Instead of accepting both instances, we need to create two methods - `addFilter` and `addSorter`. This way we don't have to check what was sent and the code will be more readable.

**Comment by Pavel910** [comment]
@adrian1358 This was fixed by simply changing parameter type to `EntityQueryManipulator` since both Filter and Sorter extend that base class. At this point there is no need for new methods. Cheers!

**Comment by adrian1358** [comment]
Great @Pavel910 ! Expecting it in the next release ;)
